services:
  backend:
    build: .
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: 123456@info
      MARIADB_ROOT_PASSWORD: 123456@info

  configurator:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    deploy:
      restart_policy:
        condition: none
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    deploy:
      restart_policy:
        condition: none
    depends_on:
      configurator:
        condition: service_completed_successfully
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "Dependencies are healthy, starting site creation...";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=123456@info --db-root-username=root --db-root-password=123456@info --install-app erpnext --set-default frontend --install-app hrms --install-app print_designer --install-app sdrt;

  db:
    image: mariadb:10.6
    networks:
      - shared-web-network
    healthcheck:
      test: mysqladmin ping -h localhost --password=123456@info
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456@info
      MARIADB_ROOT_PASSWORD: 123456@info
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    depends_on:
      create-site:
        condition: service_completed_successfully
      websocket:
        condition: service_started
      backend:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-long:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    depends_on:
      create-site:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    depends_on:
      create-site:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - shared-web-network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - shared-web-network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    depends_on:
      create-site:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: erpnext-hrms-custom:latest
    networks:
      - shared-web-network
    depends_on:
      create-site:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  shared-web-network:
    external: true
